config/routes.rb
Rails.application.routes.draw do
  
 
  resources :shows do
    resources :comments
    resources :ratings 
    resources :reviews
  end
 
  resources :reviews
 
  resources :users do
    resources :shows
  end

  get '/auth/github/callback', to: 'users#github_login'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post 'ratings', to: 'ratings#create'
  
  root 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

    validates :content, presence: true 
    validates :content, length: {minimum: 2 }

    belongs_to :user 
    belongs_to :show 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    helper_method :logged_in?, :current_user


    def new
        @user = current_user 
        @show = Show.find_by(id: params[:show_id])
        @comment = Comment.new(show_id: params[:show_id], user_id: current_user.id)
       
    end

    def create 
        @user = current_user
        @show = Show.find_by(id: params[:show_id])
        @comment = Comment.new(comment_params)
       

        if @comment.save 
            redirect_to show_path(@show)
        else
            render :new
        end
    end

    def edit 
        @user = current_user
        @show = Show.find_by(id: params[:show_id])
        @comment = @show.comments.first 
    end

    def update 
        @user = current_user
        @show = Show.find_by(id: params[:show_id])
        @comment = @show.comments.first 
        @comment.update(comment_params)
        if @comment.save 
            redirect_to show_path(@show)
        else
            render 'shows/edit'
        end
    end


    private 

        def comment_params
            params.require(:comment).permit(:content, :user_id, :show_id )
        end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% if @comment.errors.any? %>
    <ul>
        <% @comment.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for([@user, @show, @comment], :url => show_comments_path(@show), method: :post) do |f| %>
    <%= f.hidden_field :show_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.label :content, "Leave a review/comment that other users can see!" %>
    <br>
    <%= f.text_area :content %>
    <br>
    <%= f.submit "Submit Comment/Review" %>
<% end %>

app/views/comments/new.html.erb
<%= render partial: 'form' %>
<br><br><br>
<%= button_to "Cancel Comment/Review", show_path(@show), method: :get%>