config/routes.rb
Rails.application.routes.draw do
  
 
  resources :shows do
    resources :comments
    resources :ratings 
    resources :reviews
  end
 
  resources :reviews
 
  resources :users do
    resources :shows
  end

  get '/auth/github/callback', to: 'users#github_login'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post 'ratings', to: 'ratings#create'
  
  root 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    validates :username, presence: true, uniqueness: true 
    validates :full_name, presence: true
    validates :email, uniqueness: true, allow_blank: true

    has_many :shows 
    has_many :comments, through: :shows 
    has_many :ratings, through: :shows

    def favorite_shows
        @favs = []
        self.shows.each do |s|
            s.ratings.each do |r|
                if r.score >= 90
                    @favs << s 
                end
            end
        end
        return @favs.sort 
    end

    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    helper_method :logged_in?, :current_user
    
    def index
        if logged_in?
            @users = User.all 
        else
            flash[:alert] = "You must be logged in to view that page!"
            redirect_to root_path
        end
    end



    def new
        if logged_in?
            redirect_to user_shows_path(current_user)
        else
            @user = User.new
        end
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(session[:user_id])
        else
            render :new 
        end
    end

    def show
        @show_user = User.find_by(id: params[:id])
        @recent_show = @show_user.shows.finished.most_recent

        if logged_in?
            render :show 
        else
            flash[:alert] = "You must be logged in to view that page!"
            redirect_to root_path
        end
    end

    def github_login
        @user = User.find_by(username: auth[:info][:nickname])

        if @user.nil?
            @user = User.new(
                username: auth[:info][:nickname],
                full_name: auth[:info][:name],
                password: SecureRandom.uuid
            )
        end
        if @user.save 
            session[:user_id] = @user.id 
            redirect_to user_path(session[:user_id])
        else
            render :new 
        end
    end

    def edit
        @edit_user = User.find_by(id: params[:id])
        if @edit_user == current_user
            render :edit 
        else
            flash[:alert] = "You can't edit someone else's account!"
            redirect_to root_path 
        end
    end

    def update
        @user = User.find_by(id: params[:id])
        @user.update(user_params)
        if @user.save 
            redirect_to user_path(session[:user_id])
        else
            render :edit 
        end
    end


    private

        def user_params
            params.require(:user).permit(:username, :full_name, :email, :password, :password_confirmation)
        end

        def auth 
            request.env['omniauth.auth']
        end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <%= f.label :full_name, "Full Name" %>
    <%= f.text_field :full_name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "Sign Up" %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <ul>
        <% @user.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username, :readonly => true %>
    <br>
    <%= f.label :full_name, "Full Name" %>
    <%= f.text_field :full_name %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br><br>
    Enter and confirm current password, or make a new one:
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "Update Account" %>
<% end %>

<br><br>

<%= button_to "Cancel Edit", user_path(current_user), method: :get %>

app/views/users/index.html.erb
<h2>All Users</h2>

<br>

<ol>
<% @users.each do |u| %>    
    <li><button><%=link_to u.username, user_path(u) %></button>
     <br><button><%= link_to "#{u.username}'s shows", user_shows_path(u) %></button></li>
     <br><br>
<% end %>
</ol>

<br><br>
<%= button_to "All Shows", shows_path, method: :get %>
<br><br><br>
<% if logged_in? %>
    <%= button_to "Back to Your Profile", user_path(current_user), method: :get %>
    <br><br>
    <%= button_to "Back to Your Shows", user_shows_path(current_user), method: :get %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up for TV Show Tracker</h2>
<h3><strong><%= button_to "Sign Up via Github", '/auth/github' %></strong></h3>
<br>
<h3>Or enter your sign up info below:</h3>



<%= render partial: "form" %>

<br><br>

<h3>Already have an account? <%= button_to "Log In", login_path, method: :get %></h3>

app/views/users/show.html.erb
<% if @show_user == current_user  %>
    <h2><%= "Welcome to your profile, #{@show_user.full_name}!"%></h2>
<% else %>
 <h2><%= "#{@show_user.username}'s profile" %></h2>
<% end %>

<br><br>

<h3>Favorite Shows</h3>
<% if @show_user.favorite_shows.empty? %>
    <p>- No favorite shows to display! -</p>
<% else %>
    <ol>
    <% @show_user.favorite_shows.each do |s| %>
        <li><%= link_to s.name, show_path(s) %> 
        <br><%= "Rating: #{s.ratings.first.score}" %><br>
        <% if s.comments.first %>
        <%= "Review/Comment: #{s.comments.first.content}" %></li>
        <% end %>
        <br>
    <% end %>
    <br><br>
    <% if @show_user.shows.find_by(status: "Watched") %>
        Most recently finished show: <%= link_to @recent_show.first.name, show_path(@recent_show.first.id) %>
    <% end %>
    </ol>
<% end %>
<br>
<% if @show_user == current_user %>
    <%= button_to "All Your Shows", user_shows_path(@show_user), method: :get %>
    <br>
    <%= button_to "Add a New Show", new_user_show_path(@show_user), method: :get %>
<% end %>



<br><br><br>
    <%= button_to "All Shows in Database", shows_path, method: :get %>
<br><br>
    <%= button_to "Back to All Users", users_path, method: :get %>


<br><br><br><br>

<% if @show_user == current_user %>
    <%= button_to "Edit Your Account Info", edit_user_path(@user), method: :get %>
<% end %>