config/routes.rb
Rails.application.routes.draw do
  
 
  resources :shows do
    resources :comments
    resources :ratings 
    resources :reviews
  end
 
  resources :reviews
 
  resources :users do
    resources :shows
  end

  get '/auth/github/callback', to: 'users#github_login'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post 'ratings', to: 'ratings#create'
  
  root 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord


    belongs_to :show
    belongs_to :review
    validates :score, presence: true

    def review_id=(id)
        self.review = Review.find_by(id: id)
    end

    def review_id
        self.review ? self.review.id : nil
    end
    

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

    helper_method :logged_in?, :current_user
    


    def new
            
        @show = Show.find_by(id: params[:show_id])
        @rating = Rating.new(show_id: params[:show_id] )       
        @review = Review.new 
        @review.shows << @show 
        
        @shows = Show.all 
        @reviews = Review.all 
        
    end

    def create
        @show = Show.find_by(id: params[:show_id])
        @rating = Rating.new(rating_params)
        @review = Review.find_by(id: params[:rating][:review_id]) 
        @review.ratings << @rating 
        if @rating.save 
            redirect_to show_path(@rating.show_id)
        else
            render 'shows/new'
        end
    end

    def edit 
        @show = Show.find_by(id: params[:show_id])
        @rating = @show.ratings.first 
    end

    def update 
        @show = Show.find_by(id: params[:show_id])
        @rating = @show.ratings.first 
        @rating.update(rating_params)
        if @rating.save 
            redirect_to show_path(@rating.show_id)
        else
            render 'shows/edit'
        end
    end


    private

        def rating_params
            params.require(:rating).permit(:score, :show_id)
        end

        
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<% if @rating.errors.any? %>
    <ul>
        <% @rating.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>



<%= form_for([@show, @rating], :url => show_ratings_path(@show), method: :post) do |f| %>
    <%= f.hidden_field :show_id %>
    
    <%= f.label :score, "Please give the show a rating between 0 and 100: " %>
    <%= f.number_field :score, in: 0..100 %>
    <br>
    
    <br>
    <%= f.submit "Rate Show" %>
<% end %>

app/views/ratings/_revform.html.erb
<% if @rating.errors.any? %>
    <ul>
        <% @rating.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>


<%= form_for([@show, @rating], :url => show_ratings_path(@show), method: :post) do |f| %>
    <%= f.hidden_field :show_id %>
    <%= f.hidden_field :review_id %>
    <%= f.collection_select(:show_id, Show.all, :id, :name) %>
    <br>
    <%= f.collection_select(:review_id, Review.all, :id, :yes_no) %>
    <br>
    <%= f.label :score, "Please give a 0 if you agree with the rating and a 1 if you do not: " %>
    <%= f.number_field :score, in: 0..1 %>
    <br>
    
    <br>
    <%= f.submit "Rate Show" %>
<% end %>

app/views/ratings/new.html.erb
<%= render partial: 'form' %>

<br><br><br>

<%= render partial: 'revform' %>