config/routes.rb
Rails.application.routes.draw do
  
 
  resources :shows do
    resources :comments
    resources :ratings 
    resources :reviews
  end
 
  resources :reviews
 
  resources :users do
    resources :shows
  end

  get '/auth/github/callback', to: 'users#github_login'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post 'ratings', to: 'ratings#create'
  
  root 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/show.rb
class Show < ApplicationRecord

    scope :finished, -> { where(status: "Watched") }
    scope :most_recent, -> {order("created_at DESC").limit(1)}

    validates :name, presence: true
    after_validation { self.name = self.name.titleize }
    validates :genre, presence: true
    after_validation { self.genre = self.genre.titleize }
    validates :episodes, presence: true, numericality: { only_integer: true }
    before_validation { self.status = self.status.downcase }
    validates :status, presence: true, inclusion: { in: ["watching", "plan to watch", "watched"]}
    after_validation { self.status = self.status.titleize }

    belongs_to :user 
    has_many :comments, :dependent => :destroy
    has_many :ratings, :dependent => :destroy
    has_many :reviews, through: :ratings 

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

    helper_method :logged_in?, :current_user

    def index
        @user = User.find_by(id: params[:user_id])
        if @user 
            @shows = @user.shows.uniq 
            flash[:title] = "All Your Shows"
        else
            @shows = Show.all 
            flash[:title] = "All Shows in Database"
        end
    end

    def show 
        session[:current_url] = 
        @show_user = User.find_by(id: params[:user_id])
        if @show_user
            
            @show = @show_user.shows.find_by(id: params[:id])
        else
            @show = Show.all.find_by(id: params[:id])
        end
    end


    def new
        if logged_in?
            @user = current_user
            @show = Show.new(user_id: params[:user_id])
        else
            flash[:alert] = "You must be logged in to create a new show!"
            redirect_to root_path
        end
    end

    def create
        @user = User.find_by(id: session[:user_id])
        @show = @user.shows.build(show_params)
        if @show.save 
            redirect_to user_show_path(@user, @show)
        else
            render :new
        end
    end

    def edit 
        @user = User.find_by(id: params[:user_id])
        if @user == current_user
            @show = Show.find_by(id: params[:id])
            @rating = @show.ratings.first
            @comment = @show.comments.first 
        else
            flash[:alert] = "You can't edit someone else's show!"
            redirect_to root_path
        end

    end


    def update
        @show = Show.find_by(id: params[:id])
        @show.update(show_params)
        
        if @show.save 
            redirect_to show_path(@show)
        else
            render :edit
        end
    end

    def destroy
        @show = Show.find_by(id: params[:id])
        @show.destroy
        redirect_to user_shows_path(current_user)
    end


    private

        def show_params
            params.require(:show).permit(:name, :genre, :episodes, :status, :user_id)
        end


end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<% if @show.errors.any? %>
    <ul>
        <% @show.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for(@show) do |f| %>
    <%= f.hidden_field :user_id, value: @user.id %>
    
    <%= f.label :name, "Name of Show" %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <br>
    <%= f.label :episodes, "Total number of episodes"  %>
    <%= f.number_field :episodes %>
    <br>
    <%= f.label :status, "Watching, Watched, or Plan to Watch?" %>
    <%= f.text_field :status %>
    <br><br>
    <%= f.submit "Create Show" %>
<% end %>

app/views/shows/edit.html.erb
<% if @show.errors.any? %>
    <ul>
        <% @show.errors.full_messages.each do |err| %>
            <li><%= err %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for(@show) do |f| %>
    
    <%= f.label :name, "Name of Show" %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <br>
    <%= f.label :episodes, "Total number of episodes"  %>
    <%= f.number_field :episodes%>
    <br>
    <%= f.label :status, "Watching, Watched, or Plan to Watch?" %>
    <%= f.text_field :status %>
    <br><br>
    <%= f.submit "Update Show" %>
<% end %>

<br><br>

<% if !@show.ratings.empty? %>
    <%= form_for([@show, @rating]) do |f| %>
        <%= f.hidden_field :show_id %>

        <%= f.label :score, "Please give the show a rating between 0 and 100: " %>
        <%= f.number_field :score, in: 0..100 %>
        <br><br>
        <%= f.submit "Update Rating" %>
    <% end %>
<% end %>

<br><br>

<% if !@show.comments.empty? %>
    <%= form_for([@user, @show, @comment], :url => show_comment_path(@show)) do |f| %>
    <%= f.hidden_field :show_id %>
    <%= f.hidden_field :user_id, value: current_user.id %>

    <%= f.label :content, "Leave a review/comment that other users can see!" %>
    <br>
    <%= f.text_area :content %>
    <br><br>
    <%= f.submit "Update Comment/Review" %>
    <% end %>
<% end %>

<br><br><br><br>

<%= button_to "Cancel Edit", show_path(@show), method: :get%>

<br><br><br><br><br><br>

<%= button_to "DELETE SHOW", user_show_path(current_user, @show), method: :delete, data: {confirm: "Are you sure you want to delete this show from your list?"} %>

app/views/shows/index.html.erb
<% if flash[:title] %>
  <h2><%= flash[:title] %></h2>
<% end %>

<% @shows.each do |s| %>
    <ul>
        <li><%= link_to "#{s.name}", show_path(s) %><br>
        Genre: <%= s.genre%><br>
        <%= s.episodes %> episodes
        <br>
        <% if !s.ratings.empty? %>
            User Rating: <%= s.ratings.first.score %>
        <% end %>
        </li>
    </ul>
<% end %>
<br><br><br>
<%= button_to "All Shows", shows_path, method: :get %>
<br><br>
<%= button_to "All Users", users_path, method: :get %>
<br><br><br>
<% if logged_in? %>
    <%= button_to "Back to Your Profile", user_path(current_user), method: :get %>
<% end %>

app/views/shows/new.html.erb
<h2>Create New Show</h2>

<%= render partial: "form" %>

app/views/shows/show.html.erb
<h2>Name: <%= @show.name %></h2>

<h3>Genre: <%= @show.genre %></h3>

<h3>Number of episodes: <%= @show.episodes %></h3>

<h3>Created by: <%= link_to @show.user.username, user_path(@show.user) %>
<br><br>
<% if @show.user == current_user %>
    <h3>Viewing status: <%= @show.status%>
<% end %>
    <br> <br>
    <% if @show.status == "Watched" && @show.ratings.empty? && @show.user == current_user  %>
       <%= button_to "Rate Show?", new_show_rating_path(@show), method: :get, locals: {show: @show, rating: @rating } %>
        <br>
    <% elsif @show.status == "Watched" && !@show.ratings.empty? %>
        Rating: <%= @show.ratings.first.score %>/100
        <br><br>
        <% if !@show.ratings.empty? && @show.ratings.first.review.yes_no  %>
            Recommended? ===> <%= @show.ratings.first.review.yes_no.upcase %>
    
        
        <% end %>
    <% end %>
<br><br><br>

       <%= button_to "Create New Rating", new_show_rating_path(@show), method: :get %>


    <%= Rating.last.review.yes_no %>


    <br><br>


    <% if @show.status == "Watched" && @show.comments.empty? && @show.user == current_user %>
        <%= button_to "Leave a Comment/Review?", new_show_comment_path(@show), method: :get, locals: {show: @show, comment: @comment } %>
    <% elsif @show.status == "Watched" && !@show.comments.empty? %>
        <p>Comment/Review: <%= @show.comments.first.content %></p>
    <% end %>
    
<br>
    <% if @show.user == current_user && !@show.ratings.empty?  %>
        <%= button_to "Recommend?", new_show_review_path(@show), method: :get %>
    <% end %>




    <br><br>
<% if @show.user == current_user %>
    <%= button_to "Edit Show Info, Rating, and Review", edit_user_show_path(current_user, @show), method: :get%>
    <br><br><br>
<% end %>
    <%= button_to "Back to All Shows", shows_path, method: :get %>
    <br><br>
    <%= button_to "Back to Your Shows", user_shows_path(current_user), method: :get %>
    <br><br>
    <%= button_to "Back to Your Profile", user_path(current_user), method: :get %>